[tool.poetry]
name = "rcdesign"
version = "0.1.0"
description = ""
authors = ["Satish Annigeri <satish.annigeri@gmail.com>"]

[tool.poetry.dependencies]
python = ">=3.9,<3.10"
numpy = "^1.21.2"
scipy = "^1.7.1"
sympy = "^1.8"
coverage = "^5.5"
pylint = "^2.10.2"
flake8 = "^3.9.2"
pytest-cov = "^2.12.1"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
