# .github/workflows/lint.yml
name: Ruff Lint

on:
  push:
    paths:
      - 'src/rcdesign/*.py'
  pull_request:
    paths:
      - 'src/rcdesign/*.py'
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Sync dependencies
        run: uv sync --locked --dev

      - name: Run Ruff on src/
        run: uv run ruff check src/rcdesign
