# .github/workflows/test.yml
name: Run Tests with uv

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Sync dependencies
        run: uv sync --locked --all-extras --dev

      - name: Run tests with pytest
        run: uv run pytest
